name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/catalogue
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: catalogue
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/catalogue

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: go get -u github.com/FiloSottile/gvt && gvt restore && go get -v github.com/mattn/goveralls
      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF##*/}
            echo ::set-output name=tag_name::${TAG}  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: ./scripts/build.sh
      - name: Login do docker.io
        run: docker login -u abhishek138 -p ${{ secrets.DOCKER_TOKEN }}
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./docker/catalogue/Dockerfile
          #path: go/src/github.com/microservices-demo/catalogue
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            abhishek138/catlog:${{ steps.prepare.outputs.tag_name }}
            abhishek138/catlog:latest  

      #- name: Unit Test
      #  run: ./test/test.sh unit.py

     # - name: Test Docker Image
     #   run: ./test/test.sh container.py

     # - name: Submit Coveralls
      #  env:
       #   COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: goveralls -coverprofile=coverage.out -service=github

      # Push to dockerhub
      - name: Push catalogue to Docker Hub
        uses: docker/build-push-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          username: abhishek138
          password: abhishek138
          dockerfile: go/src/github.com/microservices-demo/catalogue/docker/catalogue/Dockerfile
          path: go/src/github.com/microservices-demo/catalogue
          #repository: ${{ env.GROUP }}/${{ env.REPO }}
          #tag_with_ref: true
          #tag_with_sha: true
          push: true
          tags: |
            abhishek138/catalogue:latest

      - name: Push catalogue-db to Docker Hub
        uses: docker/build-push-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          username: abhishek138
          password: abhishek138
          dockerfile: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db/Dockerfile
          path: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db
          #repository: ${{ env.GROUP }}/${{ env.REPO }}
          #tag_with_ref: true
          #tag_with_sha: true
          push: true
          tags: |
            abhishek138/cataloguedb:latest
